import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./providers/ReduxProvider";
import Cart from './components/cart/Cart';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ReactMart App",
  description: "Generated by RMUNOZ & CMADRID",
  icons: {
    icon: '/favicon.svg', // Para navegadores
    shortcut: '/favicon.svg', // Para Apple Touch (opcional)
    apple: '/favicon.svg', // Para Apple Touch (opcional)
  },  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          {children}
          {/* Client component - Cart drawer */}
          <Cart />
        </ReduxProvider>
      </body>
    </html>
  );
}
